version: '3'

services:

  server:
    image: zokradonh/ecogameserver
    stop_grace_period: 20s
    ports:
      - 3000:3000/udp
      - 3001:3001/tcp
    volumes:
      - config:/app/Configs
      - worldsave:/app/Storage


volumes:
  config:
  worldsave: